---
title: "DLM"
author: "Sky Yun"
date: "2026-04-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Library Imports
```{r}
suppressPackageStartupMessages(library(cmdstanr))
suppressPackageStartupMessages(library(bayesplot))
suppressPackageStartupMessages(library(forecast))
source("source/data_sources_and_dependencies.R")
```


## Time Series Exploratory Analysis

**Time Series Plot**
```{r}
data=dataset
plot(x=data$DATE, y=data$MSPUS, 
     ylab="Median US House Price", 
     xlab="Date", type="l")
```

- shows a slight increasing trend with slight fluctuations throughout time, potentially suggesting a Bayesian dynamic linear model (DLM)


**ACF and PACF plots of Differenced Series**
```{r}

# Predictions
log_y = log(dataset$MSPUS)

# Find best ARIMA model based on AIC
arima_best_fit = auto.arima(log_y)
arima_1_1 = arima(log_y, order=c(1, 1, 1))

# mu, ar1, ma1, ma2 parameters
summary(arima_best_fit)

# mu, ar1, ma1 parameters
summary(arima_1_1)

# Approximately Normal Residuals which statisifes
qqnorm(arima_best_fit$residuals)
qqnorm(arima_1_1$residuals)
```


## MCMC Approximation

**Compiling Model**
```{r}
log_y = log(dataset$MSPUS)
scaled_y = dataset$MSPUS

y = scaled_y

train_data=list(
  N = nrow(dataset),
  y = scaled_y
)

n_samples = 10000

dlm_mod <- cmdstan_model("source/reparam_centered_dlm_manual.stan")
```

**Sampling**
```{r}
dlm_fit <- dlm_mod$sample(
  chains=2, 
  refresh=n_samples,
  iter_warmup=2500,
  iter_sampling=n_samples,
  data=train_data
)
```

## Summary Analysis
```{r}
posterior_samples <- dlm_fit$draws(variables=c("sigma_y", "sigma_level"))

# Trace Plots
mcmc_trace(posterior_samples, facet_args=list(ncol=1)) + theme_minimal()

# Rank Plots
mcmc_rank_hist(posterior_samples) + theme_minimal()
```


```{r}
y_preds_MCMC <- dlm_fit$draws(c("y_pred"), format="draws_matrix")[1:50, ]

# plot(y_preds_MCMC)
# plot(log_y, type="l")

# print(as.data.frame(y_preds_MCMC))

# 
# mean(log_y)
# lm(log_y ~ dataset$time_index)
# sd(log_y)

ggplot(as.data.frame(log_y), aes(x=log_y)) + geom_density()

vec_mcmc = as.vector((y_preds_MCMC[7, ]))
y_pred_mcmc = as.data.frame(x = vec_mcmc)
colnames(y_pred_mcmc) = c("y_pred")

pp_check(vec_mcmc, y_preds_MCMC, fun="dens_overlay")
pp_check(log_y, y_preds_MCMC, fun="dens_overlay")

plot(y=vec_mcmc, x=dataset$time_index, type="l")
plot(y=log_y, x=dataset$time_inde, type="l")

# ggplot(y_pred_mcmc, aes(x=y_pred)) + geom_density()
# ggplot(as.data.frame(log_y), aes(x=log_y)) + geom_density()
```





