---
title: "VI_ma3"
output: pdf_document
date: "2026-04-19"
---

```{r}
suppressPackageStartupMessages(library(cmdstanr))
suppressPackageStartupMessages(library(bayesplot))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(posterior))

source("source/data_sources_and_dependencies.R")
source("scripts/one_step_prediction_functions.R")

diff_y_scaled <- diff(data_scaled$MSPUS)


train_data <- list(
  N = length(diff_y_scaled),
  y = diff_y_scaled
)

ma3_stan <- cmdstan_model("source/ma3.stan")

ma3_vi <- ma3_stan$variational(
  data = train_data,
  seed = 405,
  algorithm = "meanfield",
  iter = 10000,
  tol_rel_obj = 0.001,
  draws = 10000
)

params_of_interest <- c("mu", "theta[1]", "theta[2]", "theta[3]", "sigma")

vi_summary <- posterior::as_draws_df(ma3_vi$draws()) %>%
  dplyr::select(any_of(params_of_interest)) %>%
  tidyr::pivot_longer(everything(), names_to = "variable", values_to = "value") %>%
  dplyr::group_by(variable) %>%
  dplyr::summarise(
    mean   = mean(value),
    median = median(value),
    sd     = sd(value),
    mad    = mad(value),
    q5     = quantile(value, 0.05),
    q95    = quantile(value, 0.95),
    .groups = "drop"
  )

print(vi_summary)

vi_draws <- ma3_vi$draws(variables = params_of_interest, format = "draws_matrix")

mcmc_dens(vi_draws) +
  labs(title = "VI Posterior Approximation - MA(3)")

```

One step forcasts:
```{r}
ma3_mod_cv <- cmdstan_model("source/ma3_cross_val.stan")

N <- length(diff_y_scaled)

train_data_pred <- list(
  N      = N - 1,
  y      = diff_y_scaled[-N],
  t_pred = N - 1        
)

ma3_vi_pred <- ma3_mod_cv$variational(
  data        = train_data_pred,
  seed        = 405,
  algorithm   = "meanfield",
  iter        = 50000,
  tol_rel_obj = 0.001,
  draws       = 10000
)

y_pred_samples <- as.vector(
  ma3_vi_pred$draws(variables = "y_pred", format = "matrix")
)

test_point <- diff_y_scaled[N]

pred_summary <- data.frame(
  mean   = mean(y_pred_samples),
  median = median(y_pred_samples),
  sd     = sd(y_pred_samples),
  q5     = quantile(y_pred_samples, 0.05),
  q95    = quantile(y_pred_samples, 0.95),
  actual = test_point
)
print(pred_summary)


plot_one_step_forecast_density(
  data.frame(y_pred = y_pred_samples), 
  test_point
)

mase_vi <- compute_mase(
  data.frame(y_pred = y_pred_samples), 
  test_point
)
mase_vi
```


