---
title: "05_conclusion.Rmd"
output: pdf_document
---

# Conclusion

BLR uses several explanatory variables to explain US median house prices, while MA(3) uses the series' past error to determine temporal dependence. BLR is a regression model, and MA(3) is a time-series model. 

These two models have very different structures. For BLR, we can determine the covariate that has the largest effect, which is GDP under both SNIS and MCMC. For MA(3), we find the lag that has the largest effect, which is  $\theta_3$.

Looking at each model's forecasting performance, BLR's one-step-ahead MASE is about 1.54, and 0.81 with MCMC, 0.80 with VI for MA(3) model. Since lower MASE is better, we conclude that MA(3) performs better than BLR for forecasting.

# Limitations

The MA(3) model uses only past forecast errors to predict future prices, ignoring economic factors. Also, this model is not good at predicting far future values as it doesn't have any information long-run trends. Lastly, the dataset is relatively small. With a sample size of only 80, our one-step forecasts may not be accurate compared to the true holdout values.

# Contributions

- Lily: Worked on SNIS and VI implementation and forecasting for the two models. Wrote the literature review, did a comparison between the VI and MCMC methods for the MA(3) model. Contributed to writing and formatting the final report.

- Jason: Worked on SNIS and VI implementation and forecasting for the two models. Did a comparison between the SNIS and MCMC methods for the BLR model, and an overall comparison between the BLR and MA(3) models.

- Sky: Composed MA3 model prior and likelihood specifications and worked on both MCMC methods for BLR and MA(3) Model. Developed STAN scripts and general scripts for MCMC diagnostics and forecasting predictions. Contributed to individual interpretations of the diagnostics, sampling and forecasting values for MCMC methods.
